import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../src/styles.css";
import axios from "axios";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const apiURL = process.env.API_URL;
  if (!apiURL) {
    throw new Error("API_URL is not set");
  }
  axios.defaults.baseURL = apiURL;

  return (
    <html lang="en" className="scroll-smooth">
      <body suppressHydrationWarning={true} className={inter.className}>
        {children}
      </body>
    </html>
  );
}
